title: Joakim Buschardt Møller
email: joakim@solitune.dk
description: >-
  Joakim Buschardt Møller is a creative coder, musician, technologist and humanist.
url: "https://blog.yw.gl"
github_username:  joakimjm


theme: minima
plugins:
  - jekyll-feed