title: Atom Veto | Joakim Buschardt Møller
email: joakim@solitune.dk
description: >-
  Atom is a part of the whole; Veto is the power to say no.
url: "https://blog.atomveto.com"
github_username:  joakimjm
linkedin_username: joakimjm
show_excerpts: true
timezone: Europe/Copenhagen
theme: minima
plugins:
  - jekyll-feed